/* ==========================================================================
   Synthesised sound.
   --------------------------------------------------------------------------
   Every sound in the game is generated by the Web Audio API at runtime. No
   .mp3 files, no network requests, no licensing questions, no loading state
   — the same approach fortune-teller used for its cinematic score.

   Browsers refuse to start an AudioContext before a user gesture, so the
   context is created lazily on the first real interaction and everything
   before that is a silent no-op rather than an error.
   ========================================================================== */

import { AUDIO } from "./config.js";

class Sound {
  constructor() {
    this.ctx = null;
    this.master = null;
    this.enabled = true;
    this._hum = null;
  }

  /** Called from a click/keydown handler — the only place a context may start. */
  unlock() {
    if (this.ctx) {
      if (this.ctx.state === "suspended") this.ctx.resume();
      return;
    }
    const AC = window.AudioContext || window.webkitAudioContext;
    if (!AC) return;
    try {
      this.ctx = new AC();
      this.master = this.ctx.createGain();
      this.master.gain.value = this.enabled ? AUDIO.masterGain : 0;
      this.master.connect(this.ctx.destination);
    } catch (err) {
      console.warn("[audio] unavailable", err);
      this.ctx = null;
    }
  }

  setEnabled(on) {
    this.enabled = !!on;
    if (this.master && this.ctx) {
      this.master.gain.setTargetAtTime(this.enabled ? AUDIO.masterGain : 0, this.ctx.currentTime, 0.02);
    }
    if (!this.enabled) this.stopHum();
  }

  /** One shaped oscillator burst. The building block for everything below. */
  _blip({ freq, decay, type, gain, detune = 0, when = 0, sweepTo = null }) {
    if (!this.ctx || !this.enabled) return;
    const t = this.ctx.currentTime + when;
    const osc = this.ctx.createOscillator();
    const env = this.ctx.createGain();

    osc.type = type;
    osc.frequency.setValueAtTime(freq, t);
    if (sweepTo) osc.frequency.exponentialRampToValueAtTime(Math.max(1, sweepTo), t + decay);
    osc.detune.value = detune;

    env.gain.setValueAtTime(0.0001, t);
    env.gain.exponentialRampToValueAtTime(Math.max(0.0001, gain), t + 0.008);
    env.gain.exponentialRampToValueAtTime(0.0001, t + decay);

    osc.connect(env);
    env.connect(this.master);
    osc.start(t);
    osc.stop(t + decay + 0.05);
  }

  /* ---- Cues -------------------------------------------------------------- */

  /** A single tumbler falling — used for option hover and each ladder step. */
  tumbler() { this._blip({ ...AUDIO.tumbler }); }

  tick() { this._blip({ ...AUDIO.tick }); }

  /** Rising three-note figure. Pitch climbs with the streak, so a long run
      audibly escalates without any extra assets. */
  correct(streak = 1) {
    const cfg = AUDIO.correct;
    const step = Math.min(streak, 6);
    for (let i = 0; i < 3; i++) {
      this._blip({
        ...cfg,
        freq: cfg.freq * Math.pow(2, (i * 4 + step * 1) / 12),
        decay: cfg.decay * 0.5,
        gain: cfg.gain * (1 - i * 0.15),
        when: i * 0.062,
      });
    }
  }

  wrong() {
    this._blip({ ...AUDIO.wrong, sweepTo: AUDIO.wrong.freq * 0.4 });
    this._blip({ ...AUDIO.klaxon, when: 0.05, decay: 0.35 });
    this._blip({ ...AUDIO.klaxon, when: 0.34, decay: 0.35 });
  }

  timeout() {
    this._blip({ ...AUDIO.klaxon, decay: 0.7, sweepTo: AUDIO.klaxon.freq * 0.5 });
  }

  /** Low heartbeat thud while the clock is critical. */
  heartbeat() {
    this._blip({ ...AUDIO.heartbeat, sweepTo: AUDIO.heartbeat.freq * 0.6 });
  }

  drill() {
    if (!this.ctx || !this.enabled) return;
    /* A short noise-ish burst by stacking detuned saws. */
    for (let i = 0; i < 4; i++) {
      this._blip({ ...AUDIO.drill, detune: (i - 1.5) * 40, gain: AUDIO.drill.gain / 2, when: i * 0.01 });
    }
  }

  /** Cash-register ascent when the haul is banked. */
  bankIt() {
    const cfg = AUDIO.bank;
    AUDIO.fanfare.forEach((semi, i) => {
      this._blip({
        ...cfg,
        freq: cfg.freq * Math.pow(2, semi / 12),
        decay: 0.34,
        gain: cfg.gain * 0.7,
        when: i * 0.075,
      });
    });
  }

  /** Deep rumble as the door swings — run cleared. */
  vaultOpen() {
    this._blip({ ...AUDIO.vault, sweepTo: AUDIO.vault.freq * 2.4 });
    this.bankIt();
  }

  /** Slam — run busted. */
  lockdown() {
    this._blip({ ...AUDIO.vault, decay: 1.4, sweepTo: AUDIO.vault.freq * 0.4 });
    this._blip({ ...AUDIO.klaxon, when: 0.12, decay: 0.8 });
  }

  /* ---- Tension hum -------------------------------------------------------
     A single low oscillator whose gain tracks the game's heat value. Costs
     one node for the whole session and does more for tension than any
     number of one-shots. */

  startHum() {
    if (!this.ctx || !this.enabled || this._hum) return;
    const osc = this.ctx.createOscillator();
    const gain = this.ctx.createGain();
    osc.type = "sine";
    osc.frequency.value = 52;
    gain.gain.value = 0;
    osc.connect(gain);
    gain.connect(this.master);
    osc.start();
    this._hum = { osc, gain };
  }

  setHeat(heat) {
    if (!this._hum || !this.ctx) return;
    this._hum.gain.gain.setTargetAtTime(Math.min(0.22, heat * 0.22), this.ctx.currentTime, 0.25);
    this._hum.osc.frequency.setTargetAtTime(52 + heat * 16, this.ctx.currentTime, 0.4);
  }

  stopHum() {
    if (!this._hum) return;
    try {
      this._hum.gain.gain.setTargetAtTime(0, this.ctx.currentTime, 0.1);
      const { osc } = this._hum;
      setTimeout(() => { try { osc.stop(); } catch { /* already stopped */ } }, 400);
    } catch { /* context closed */ }
    this._hum = null;
  }
}

export const sound = new Sound();
