/* ==========================================================================
   Sound.
   --------------------------------------------------------------------------
   Two sources, in priority order:

     1. FILES in assets/audio/ — if a Suno-generated music bed or a rendered
        SFX is present, it is used. Nothing needs to change in code; the
        loader probes for them at unlock and swaps them in.
     2. SYNTHESIS — the fallback, and what ships today. Everything is
        generated by the Web Audio API at runtime: no network, no loading
        state, no licensing.

   The synthesis here is deliberately not "an oscillator with a decay". A bare
   sine burst reads as a test tone, which is exactly what made the first pass
   sound cheap. Every cue is layered: a noise transient for the attack, a
   filtered body for the tone, and a shared reverb send so the whole thing
   sits in one room rather than a dry line-level beep.
   ========================================================================== */

import { AUDIO } from "./config.js";

/* Files the loader will use if they exist. Drop a matching file in and it
   takes over automatically — see docs/ASSETS.md for the generation prompts. */
export const AUDIO_FILES = {
  themeTitle:  "assets/audio/theme-title.mp3",
  bedTension:  "assets/audio/bed-tension.mp3",
  stingWin:    "assets/audio/sting-vault-open.mp3",
  stingLose:   "assets/audio/sting-lockdown.mp3",
};

class Sound {
  constructor() {
    this.ctx = null;
    this.master = null;
    this.reverb = null;
    this.reverbSend = null;
    this.enabled = true;
    this._hum = null;
    this._buffers = new Map();
    this._music = null;
    this._musicGain = null;
    this._musicShelf = null;
    this._musicPresence = null;
    this._probed = false;
  }

  /* ---- Graph ------------------------------------------------------------- */

  unlock() {
    if (this.ctx) {
      if (this.ctx.state === "suspended") this.ctx.resume();
      return;
    }
    const AC = window.AudioContext || window.webkitAudioContext;
    if (!AC) return;

    try {
      this.ctx = new AC();

      this.master = this.ctx.createGain();
      this.master.gain.value = this.enabled ? AUDIO.masterGain : 0;

      /* A gentle limiter keeps stacked cues from clipping when a correct
         answer, a coin rain and a streak popup all fire on the same frame. */
      const comp = this.ctx.createDynamicsCompressor();
      comp.threshold.value = -14;
      comp.knee.value = 22;
      comp.ratio.value = 8;
      comp.attack.value = 0.003;
      comp.release.value = 0.18;

      this.master.connect(comp);
      comp.connect(this.ctx.destination);

      /* One shared plate reverb. Sends, not inserts, so dry transients stay
         punchy while tails share a room. */
      this.reverb = this.ctx.createConvolver();
      this.reverb.buffer = this._makeImpulse(1.9, 2.6);
      this.reverbSend = this.ctx.createGain();
      this.reverbSend.gain.value = 0.3;
      this.reverbSend.connect(this.reverb);
      this.reverb.connect(this.master);

      this._probeFiles();
    } catch (err) {
      console.warn("[audio] unavailable", err);
      this.ctx = null;
    }
  }

  /** Exponentially decaying noise — a serviceable plate impulse response. */
  _makeImpulse(seconds, decay) {
    const rate = this.ctx.sampleRate;
    const len = Math.floor(rate * seconds);
    const buf = this.ctx.createBuffer(2, len, rate);
    for (let ch = 0; ch < 2; ch++) {
      const data = buf.getChannelData(ch);
      for (let i = 0; i < len; i++) {
        data[i] = (Math.random() * 2 - 1) * Math.pow(1 - i / len, decay);
      }
    }
    return buf;
  }

  /** Short noise buffer, reused for every transient. */
  _noiseBuffer(seconds = 0.4) {
    const key = `noise:${seconds}`;
    if (this._buffers.has(key)) return this._buffers.get(key);
    const rate = this.ctx.sampleRate;
    const len = Math.max(1, Math.floor(rate * seconds));
    const buf = this.ctx.createBuffer(1, len, rate);
    const data = buf.getChannelData(0);
    for (let i = 0; i < len; i++) data[i] = Math.random() * 2 - 1;
    this._buffers.set(key, buf);
    return buf;
  }

  setEnabled(on) {
    this.enabled = !!on;
    if (this.master && this.ctx) {
      this.master.gain.setTargetAtTime(this.enabled ? AUDIO.masterGain : 0, this.ctx.currentTime, 0.02);
    }
    if (!this.enabled) { this.stopHum(); this.stopMusic(); }
  }

  /* ---- Optional audio files ---------------------------------------------
     A HEAD request per slot at unlock. Missing files are the normal case, so
     a 404 is not an error — it just means synthesis stays in charge. */

  async _probeFiles() {
    if (this._probed) return;
    this._probed = true;

    /* One GET per slot, not a HEAD followed by a GET — a 404 body is a few
       bytes, so the HEAD saved nothing and doubled the request count. All
       four run concurrently; a missing file is the expected case, not an
       error, so failures are swallowed and synthesis stays in charge. */
    await Promise.all(
      Object.entries(AUDIO_FILES).map(async ([name, url]) => {
        try {
          const res = await fetch(url);
          if (!res.ok) return;
          const arr = await res.arrayBuffer();
          if (!arr.byteLength) return;
          this._buffers.set(name, await this.ctx.decodeAudioData(arr));
          console.info(`[audio] using ${url}`);
        } catch { /* not present, or undecodable — synthesis handles it */ }
      })
    );
  }

  hasFile(name) { return this._buffers.has(name); }

  /* ---- Primitives --------------------------------------------------------- */

  /**
   * A tone layer: oscillator through a filter, with an ADSR-ish envelope and
   * an optional pitch sweep.
   */
  _tone({ freq, decay, type = "sine", gain = 0.2, when = 0, sweepTo = null,
          filter = null, q = 1, send = 0.25, attack = 0.006, detune = 0 }) {
    if (!this.ctx || !this.enabled) return;
    const t = this.ctx.currentTime + when;

    const osc = this.ctx.createOscillator();
    osc.type = type;
    osc.frequency.setValueAtTime(freq, t);
    osc.detune.value = detune;
    if (sweepTo) osc.frequency.exponentialRampToValueAtTime(Math.max(1, sweepTo), t + decay);

    const env = this.ctx.createGain();
    env.gain.setValueAtTime(0.0001, t);
    env.gain.exponentialRampToValueAtTime(Math.max(0.0001, gain), t + attack);
    env.gain.exponentialRampToValueAtTime(0.0001, t + decay);

    let node = osc;
    if (filter) {
      const bq = this.ctx.createBiquadFilter();
      bq.type = filter.type || "lowpass";
      bq.frequency.setValueAtTime(filter.from ?? filter.freq ?? 1200, t);
      if (filter.to) bq.frequency.exponentialRampToValueAtTime(Math.max(40, filter.to), t + decay);
      bq.Q.value = q;
      node.connect(bq);
      node = bq;
    }
    node.connect(env);
    env.connect(this.master);
    if (send > 0 && this.reverbSend) {
      const s = this.ctx.createGain();
      s.gain.value = send;
      env.connect(s);
      s.connect(this.reverbSend);
    }

    osc.start(t);
    osc.stop(t + decay + 0.06);
  }

  /**
   * A noise layer — the attack transient. This is the difference between a
   * "click" and a "beep": real impacts start with broadband noise.
   */
  _noise({ decay = 0.06, gain = 0.2, when = 0, type = "bandpass",
           from = 3000, to = 600, q = 1.2, send = 0.15 }) {
    if (!this.ctx || !this.enabled) return;
    const t = this.ctx.currentTime + when;

    const src = this.ctx.createBufferSource();
    src.buffer = this._noiseBuffer(Math.max(0.05, decay + 0.05));

    const bq = this.ctx.createBiquadFilter();
    bq.type = type;
    bq.frequency.setValueAtTime(from, t);
    bq.frequency.exponentialRampToValueAtTime(Math.max(40, to), t + decay);
    bq.Q.value = q;

    const env = this.ctx.createGain();
    env.gain.setValueAtTime(gain, t);
    env.gain.exponentialRampToValueAtTime(0.0001, t + decay);

    src.connect(bq);
    bq.connect(env);
    env.connect(this.master);
    if (send > 0 && this.reverbSend) {
      const s = this.ctx.createGain();
      s.gain.value = send;
      env.connect(s);
      s.connect(this.reverbSend);
    }

    src.start(t);
    src.stop(t + decay + 0.06);
  }

  _playBuffer(name, { gain = 0.8, when = 0 } = {}) {
    const buf = this._buffers.get(name);
    if (!buf || !this.ctx || !this.enabled) return false;
    const src = this.ctx.createBufferSource();
    src.buffer = buf;
    const g = this.ctx.createGain();
    g.gain.value = gain;
    src.connect(g);
    g.connect(this.master);
    src.start(this.ctx.currentTime + when);
    return true;
  }

  /* ---- Cues ---------------------------------------------------------------- */

  /** A lock tumbler dropping: metal tick + short pitched body. */
  tumbler() {
    this._noise({ decay: 0.035, gain: 0.34, from: 6500, to: 1800, q: 2.4, send: 0.1 });
    this._tone({ freq: 1180, decay: 0.06, type: "triangle", gain: 0.1, send: 0.18,
                 filter: { type: "bandpass", from: 1400, to: 900 }, q: 3 });
  }

  tick() {
    this._noise({ decay: 0.014, gain: 0.1, from: 7000, to: 4000, q: 3, send: 0.05 });
  }

  /**
   * Correct: a struck metal chord that climbs with the streak. Three
   * detuned partials plus a bright transient — the detune is what makes it
   * read as a struck object rather than a synth note.
   */
  correct(streak = 1) {
    const step = Math.min(streak, 7);
    const root = 392 * Math.pow(2, step / 12);   /* G4, rising per streak */

    this._noise({ decay: 0.05, gain: 0.3, from: 8000, to: 2200, q: 1.6, send: 0.2 });

    [0, 7, 12].forEach((semi, i) => {
      const f = root * Math.pow(2, semi / 12);
      this._tone({
        freq: f, decay: 0.9 - i * 0.16, type: "triangle",
        gain: 0.16 - i * 0.035, when: i * 0.028, send: 0.42,
        filter: { type: "lowpass", from: 5200, to: 1400 }, detune: (i - 1) * 6,
      });
      /* A quiet sine an octave up gives the chime its shine. */
      this._tone({ freq: f * 2, decay: 0.5, type: "sine", gain: 0.05, when: i * 0.028, send: 0.5 });
    });
  }

  /** Wrong: a heavy mechanical clunk, then the bolt refusing. */
  wrong() {
    this._noise({ decay: 0.11, gain: 0.42, from: 1800, to: 180, q: 0.8, send: 0.2 });
    this._tone({ freq: 150, decay: 0.42, type: "sawtooth", gain: 0.24, sweepTo: 58,
                 send: 0.28, filter: { type: "lowpass", from: 900, to: 180 } });
    this._tone({ freq: 96, decay: 0.6, type: "square", gain: 0.13, when: 0.05, send: 0.3,
                 filter: { type: "lowpass", from: 500, to: 140 } });
  }

  /** Timeout: two falling klaxon blasts. */
  timeout() {
    for (let i = 0; i < 2; i++) {
      this._tone({ freq: 420, decay: 0.34, type: "square", gain: 0.16, when: i * 0.3,
                   sweepTo: 250, send: 0.35, filter: { type: "lowpass", from: 1800, to: 700 } });
      this._tone({ freq: 421.5, decay: 0.34, type: "square", gain: 0.1, when: i * 0.3,
                   sweepTo: 251, send: 0.35, detune: 12 });
    }
  }

  /** Low chest thud while the clock is critical. */
  heartbeat() {
    this._tone({ freq: 68, decay: 0.24, type: "sine", gain: 0.4, sweepTo: 38, send: 0.1,
                 filter: { type: "lowpass", from: 220, to: 70 } });
    this._noise({ decay: 0.05, gain: 0.06, from: 400, to: 120, q: 0.7, send: 0.08 });
  }

  /** Drill: filtered noise burst with a motor whine. */
  drill() {
    this._noise({ decay: 0.42, gain: 0.24, type: "bandpass", from: 1400, to: 380, q: 0.9, send: 0.2 });
    this._tone({ freq: 180, decay: 0.42, type: "sawtooth", gain: 0.1, sweepTo: 320, send: 0.15,
                 filter: { type: "lowpass", from: 1200, to: 2600 } });
    this._tone({ freq: 182, decay: 0.42, type: "sawtooth", gain: 0.08, sweepTo: 324, detune: 18, send: 0.15 });
  }

  /** Banked: a rising arpeggio over a register-drawer thunk. */
  bankIt() {
    this._noise({ decay: 0.09, gain: 0.24, from: 2600, to: 500, q: 1.1, send: 0.2 });
    AUDIO.fanfare.forEach((semi, i) => {
      const f = 523.25 * Math.pow(2, semi / 12);
      this._tone({ freq: f, decay: 0.42, type: "triangle", gain: 0.15, when: i * 0.072,
                   send: 0.45, filter: { type: "lowpass", from: 6000, to: 2000 } });
      this._tone({ freq: f * 2, decay: 0.24, type: "sine", gain: 0.045, when: i * 0.072, send: 0.5 });
    });
  }

  /** Vault opening: sub rumble, servo sweep, then the payoff arpeggio. */
  vaultOpen() {
    if (this._playBuffer("stingWin", { gain: 0.9 })) return;
    this._tone({ freq: 36, decay: 2.4, type: "sawtooth", gain: 0.3, sweepTo: 92, send: 0.3,
                 filter: { type: "lowpass", from: 180, to: 900 } });
    this._noise({ decay: 1.5, gain: 0.14, type: "bandpass", from: 300, to: 2400, q: 0.7, send: 0.4 });
    this.bankIt();
  }

  /** Lockdown: bolts slamming home, then the alarm. */
  lockdown() {
    if (this._playBuffer("stingLose", { gain: 0.9 })) return;
    this._noise({ decay: 0.2, gain: 0.5, from: 2200, to: 120, q: 0.7, send: 0.25 });
    this._tone({ freq: 84, decay: 1.5, type: "sawtooth", gain: 0.3, sweepTo: 30, send: 0.35,
                 filter: { type: "lowpass", from: 700, to: 90 } });
    for (let i = 0; i < 3; i++) {
      this._tone({ freq: 300, decay: 0.3, type: "square", gain: 0.12, when: 0.22 + i * 0.34,
                   sweepTo: 210, send: 0.4 });
    }
  }

  /* ---- Tension bed ---------------------------------------------------------
     Two detuned oscillators through a lowpass whose cutoff tracks heat. One
     voice pair for the whole session, and it does more for tension than any
     number of one-shots.                                                     */

  startHum() {
    if (!this.ctx || !this.enabled || this._hum) return;
    /* The hum is a SUBSTITUTE for a music bed, not a companion to one. With a
       Suno bed playing, its 49 Hz saw stacks under the track's own bass and
       heat pushes it louder still — audibly boomy within a couple of
       questions. When a bed is playing, tension is expressed by shaping the
       bed instead (see setHeat). */
    if (this._music) return;

    const gain = this.ctx.createGain();
    gain.gain.value = 0;

    const filter = this.ctx.createBiquadFilter();
    filter.type = "lowpass";
    filter.frequency.value = 220;
    filter.Q.value = 3;

    const oscs = [0, 1].map((i) => {
      const o = this.ctx.createOscillator();
      o.type = i === 0 ? "sawtooth" : "sine";
      o.frequency.value = i === 0 ? 49 : 98;
      o.detune.value = i === 0 ? -6 : 5;
      o.connect(filter);
      o.start();
      return o;
    });

    filter.connect(gain);
    gain.connect(this.master);
    if (this.reverbSend) {
      const s = this.ctx.createGain();
      s.gain.value = 0.2;
      gain.connect(s);
      s.connect(this.reverbSend);
    }
    this._hum = { oscs, gain, filter };
  }

  setHeat(heat) {
    if (!this.ctx) return;
    const t = this.ctx.currentTime;

    /* With a bed playing, tension TIGHTENS the mix rather than adding to it:
       the low shelf comes down as heat rises, which reads as urgency without
       any extra low end, and a touch of presence comes up instead. */
    if (this._music && this._musicShelf) {
      this._musicShelf.gain.setTargetAtTime(-10 * heat, t, 0.5);
      this._musicPresence.gain.setTargetAtTime(3.5 * heat, t, 0.5);
      return;
    }

    if (!this._hum) return;
    this._hum.gain.gain.setTargetAtTime(Math.min(0.2, 0.03 + heat * 0.17), t, 0.3);
    this._hum.filter.frequency.setTargetAtTime(200 + heat * 900, t, 0.4);
    this._hum.oscs[0].detune.setTargetAtTime(-6 - heat * 22, t, 0.5);
  }

  stopHum() {
    if (!this._hum) return;
    try {
      this._hum.gain.gain.setTargetAtTime(0, this.ctx.currentTime, 0.12);
      const { oscs } = this._hum;
      setTimeout(() => oscs.forEach((o) => { try { o.stop(); } catch { /* already stopped */ } }), 500);
    } catch { /* context closed */ }
    this._hum = null;
  }

  /* ---- Music bed (file-backed only) ---------------------------------------- */

  playMusic(name, { loop = true, gain = 0.32 } = {}) {
    if (!this.ctx || !this.enabled) return false;
    const buf = this._buffers.get(name);
    if (!buf) return false;
    this.stopMusic();

    const src = this.ctx.createBufferSource();
    src.buffer = buf;
    src.loop = loop;

    /* Tone shaping the bed passes through, so heat can tighten it without
       adding another voice to the low end. */
    const shelf = this.ctx.createBiquadFilter();
    shelf.type = "lowshelf";
    shelf.frequency.value = 160;
    shelf.gain.value = 0;

    const presence = this.ctx.createBiquadFilter();
    presence.type = "peaking";
    presence.frequency.value = 1800;
    presence.Q.value = 0.9;
    presence.gain.value = 0;

    const g = this.ctx.createGain();
    g.gain.setValueAtTime(0.0001, this.ctx.currentTime);
    g.gain.exponentialRampToValueAtTime(gain, this.ctx.currentTime + 1.2);

    src.connect(shelf);
    shelf.connect(presence);
    presence.connect(g);
    g.connect(this.master);
    src.start();

    this._music = src;
    this._musicGain = g;
    this._musicShelf = shelf;
    this._musicPresence = presence;

    /* A bed supersedes the synthesised hum — never both. */
    this.stopHum();
    return true;
  }

  stopMusic() {
    if (!this._music) return;
    try {
      const src = this._music;
      this._musicGain.gain.setTargetAtTime(0, this.ctx.currentTime, 0.3);
      setTimeout(() => { try { src.stop(); } catch { /* already stopped */ } }, 900);
    } catch { /* context closed */ }
    this._music = null;
    this._musicGain = null;
    this._musicShelf = null;
    this._musicPresence = null;
  }
}

export const sound = new Sound();
