/* ==========================================================================
   Author the INFORMANT clues.
   Usage:  node scripts/author-hints.mjs [--dry] [--report]

   One real hint per question, written by hand and stored in the bank as a
   `hint` field. Etch (the opening letter) is derived at runtime and needs no
   data; this is the half that cannot be computed.

   The hard rule, enforced below: a hint must never contain the answer or any
   of its accepted aliases. A hint that gives away the answer is not a hint,
   it is the answer with extra steps — and since Informant costs a lifeline,
   shipping one would be worse than shipping none.
   ========================================================================== */

import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const here = dirname(fileURLToPath(import.meta.url));
const bankPath = join(here, "..", "data", "questions.json");
const bank = JSON.parse(readFileSync(bankPath, "utf8"));

const dry = process.argv.includes("--dry");
const report = process.argv.includes("--report");

/* ---- The hints ----------------------------------------------------------- */

export const HINTS = {
  /* ---- Technology --------------------------------------------------------- */
  101: "Often called the computer's brain; it executes the instructions.",
  102: "Volatile working memory — it empties the moment power is lost.",
  103: "It is what the padlock icon in the address bar is promising.",
  104: "A British scientist who built it at CERN in 1989.",
  105: "Named after a British comedy troupe, not the snake.",
  106: "He wrote it in 2005 to manage the Linux kernel's source.",
  107: "The language you are writing when you type SELECT.",
  108: "Daughter of the poet Byron; collaborated with Charles Babbage.",
  109: "Four binary digits, and the value is a power of two.",
  110: "Successor to an 8-bit machine, with the bit-width doubled.",
  313: "The three letters people used to say before every web address.",
  314: "The field that machine learning and chatbots belong to.",
  315: "A Japanese electronics giant that also makes cameras and TVs.",
  316: "He went on to become the world's richest man, then a philanthropist.",
  317: "He designed the Apple I circuit board single-handedly.",
  318: "The connector nobody manages to insert the right way up first time.",
  319: "Adobe invented it so a document looks identical everywhere.",
  320: "A Kyoto company that began by making playing cards in 1889.",
  509: "Memory you can read from but cannot write to.",
  510: "A US Navy rear admiral who also worked on COBOL.",
  511: "The looping animated image format, born on CompuServe.",
  512: "A Santa Clara chipmaker whose name shortens 'integrated electronics'.",
  513: "The web address itself — the thing you type into the bar.",
  514: "It replaced DES as the US government's cipher standard.",
  515: "The language academics reach for to run regressions and draw plots.",
  516: "It concerns access to the code, not the price of the software.",
  517: "Four letters, and the first one stands for Dynamic.",
  518: "An American company that took its name from a term in Go.",
  666: "Paired with IP; it guarantees packets arrive in the right order.",
  667: "Average case O(n log n); Tony Hoare devised it in 1959.",
  668: "The same year the first Kindle shipped.",
  669: "The contract one piece of software offers another.",
  670: "The research arm of the American telephone monopoly.",
  671: "Picture a pile of plates — you can only take from the top.",
  672: "The numeric addresses that machines actually route packets to.",
  673: "Haskell is the purest mainstream example of it.",
  674: "It holds either a one or a zero, and nothing else.",
  676: "Its object-oriented successor added classes and two plus signs.",
  675: "Spreading data across several disks, for speed or for safety.",

  /* ---- Language & Words --------------------------------------------------- */
  91:  "'Racecar' and 'level' both qualify.",
  92:  "Comic books are full of them: pow, splat, whoosh.",
  93:  "Named after a 9th-century missionary saint.",
  94:  "It runs from alpha to omega — two more than English has minus two.",
  95:  "Not what a word means now, but where it came from.",
  96:  "Two Latin words meaning roughly 'for the sake of example'.",
  97:  "Over a billion speakers, concentrated in one country.",
  98:  "Invented by L. L. Zamenhof so no nation would own it.",
  99:  "A poetic phrase about the organ that beats, not the stomach.",
  100: "English is stuffed with them: 'ballet', 'karaoke', 'kindergarten'.",
  306: "One for each letter from A to Z.",
  307: "Y is sometimes counted a sixth, which tells you the shape of the answer.",
  308: "Same tongue as its large northern neighbour.",
  309: "French, and it is what you do when invited to a wedding.",
  310: "Latin for 'before midday'.",
  311: "Latin, and it is what you write when the list gets too long.",
  312: "Like 'foot' becomes 'feet', not by adding an s.",
  499: "'Bank' the riverside and 'bank' the vault are one of these.",
  500: "From the Greek 'bios'; think biology and biography.",
  501: "Commissioned by King Sejong in the 15th century.",
  502: "Not meant literally — nobody has told you that many times.",
  503: "Latin for turning the order of two things around.",
  504: "The same source language gave English 'honcho' and 'tsunami'.",
  505: "Unlike an initialism, you say it as a word: NATO, SCUBA.",
  506: "Enough to read a newspaper; the full set runs to tens of thousands.",
  507: "'The quick brown fox jumps over the lazy dog' is the famous one.",
  508: "Hot and cold, up and down — the opposite of a synonym.",
  656: "'Their', 'there' and 'they're' are the classic trio.",
  657: "Not Indo-European; Estonian belongs to it too.",
  658: "Smaller than a word: the 'un-' in 'unhappy' is one.",
  659: "Two of its three scripts are syllabaries; one is borrowed from China.",
  660: "'Kick the bucket' has nothing to do with buckets.",
  661: "Grammar's rules of order, not of meaning.",
  662: "More than Mandarin's four, and Cantonese speakers argue about the count.",
  663: "'Dust' can mean to add dust or remove it.",
  664: "Tracing sound shifts and meaning drift across centuries.",
  665: "Like 'hoover', 'escalator' and 'aspirin' before it.",

  /* ---- Sports & Games ----------------------------------------------------- */
  81:  "Ten outfield players plus the one in gloves.",
  82:  "It stays on its starting colour for the whole game.",
  83:  "Possibly from the French for egg, after the shape of a nought.",
  84:  "Five titles, more than anyone else, and the only country at every finals.",
  85:  "Front nine plus back nine.",
  86:  "Three disciplines in one race, finishing on foot.",
  87:  "Black and white, placed on intersections rather than squares.",
  88:  "One fewer than a Scrabble bingo needs to use them all plus a board letter.",
  89:  "Its name translates roughly as 'the way of the foot and fist'.",
  90:  "The same term football uses for three goals, but far rarer.",
  296: "Two guards, two forwards, one centre.",
  297: "One for each inhabited continent, interlocked.",
  298: "Grass courts, strawberries and cream, all-white clothing.",
  299: "The same interval as a US presidential term.",
  300: "Played on ice, with a rubber disc instead of a ball.",
  301: "Pelé used the phrase as the title of his autobiography.",
  302: "He lit the Atlanta Olympic flame in 1996 and refused the Vietnam draft.",
  303: "The country that invented the ancient games hosted the revival.",
  304: "A bird you might eat at Thanksgiving.",
  305: "Eight forwards and seven backs.",
  487: "Ten spaces per side of the square board.",
  488: "Three treble twenties.",
  489: "Exactly twice the diameter of the ball, near enough.",
  490: "It began there in the 1880s as a genteel indoor substitute for lawn tennis.",
  491: "It ends the game as a draw, not a win.",
  492: "One fewer than a football team's outfield half, per side.",
  493: "Named after a Governor General of Canada.",
  494: "Contested between the United States and Europe every two years.",
  495: "Founded by Jigoro Kano; the throws matter more than the strikes.",
  496: "They fill the first three rows of dark squares.",
  497: "Twelve strikes in a row.",
  498: "The fielding side wears white and the match can last five days.",
  645: "Three blades: one thrusting weapon scores with the point only, one cuts.",
  646: "It has hosted the Summer Games four times and leads the all-time table.",
  647: "Twenty-six miles and 385 yards, converted.",
  648: "A waterfowl whose egg shape stands in for a nought.",
  649: "Six outfield players plus a goalkeeper.",
  650: "Run at Churchill Downs on the first Saturday in May.",
  651: "A circle of packed clay, about 4.55 metres across.",
  652: "Fifteen reds each followed by a black, then all the colours.",
  653: "Three of them make up a full game.",
  654: "Black's most popular reply to the king's pawn opening.",
  655: "A Japanese rule preventing an endless capture-and-recapture loop.",

  /* ---- Geography ---------------------------------------------------------- */
  1:   "It alone covers about an eighth of the world's inhabited land.",
  2:   "One side calls the peak Sagarmatha, the other Chomolungma.",
  3:   "Barely 13 km across at its narrowest; a famous rock guards its north side.",
  4:   "Nearly 9,000 km of it, much drawn along the 49th parallel.",
  5:   "The world's coldest capital, in a landlocked country of steppe.",
  6:   "One of only three countries entirely enclosed by a single other.",
  7:   "It holds roughly a fifth of the world's unfrozen fresh water.",
  8:   "Its scattered overseas departments stretch from the Pacific to the Caribbean.",
  9:   "A former Dutch colony on the northeast shoulder of the continent.",
  10:  "The only city sitting on two continents at once.",
  201: "A compromise: neither Sydney nor Melbourne got it.",
  202: "It covers more of the planet than all the land combined.",
  203: "You could walk across it in twenty minutes; it has a Swiss Guard.",
  204: "Home to about 60% of humanity.",
  205: "Not Toronto, and not Montreal.",
  206: "Its own name for itself, Nihon, means roughly the same thing.",
  207: "More than twice the size of the second-largest.",
  208: "Measured from sea level, not from the Earth's centre.",
  209: "It flows north, through eleven countries.",
  210: "Roughly the area of the United States, and it is growing.",
  211: "Purpose-built inland in the 1950s, shaped like an aeroplane from above.",
  212: "It was 28 before one member left in 2020.",
  213: "The West Bank lies between them.",
  214: "It defeated an Italian invasion at Adwa in 1896.",
  215: "It runs for thousands of kilometres and is not, in fact, visible from space.",
  351: "All those Arctic islands add up.",
  352: "Called a sea, but landlocked and technically a lake.",
  353: "It opened in 1869 and saves ships the trip round the Cape.",
  354: "About 430 metres below sea level, and still dropping.",
  355: "Over 200,000 of them, most in its Baltic archipelagos.",
  356: "Renamed twice in thirty years; a purpose-built steppe capital.",
  357: "Autonomous, but part of the Danish realm.",
  358: "Its name means 'in the middle of the earth'.",
  359: "Visible from orbit and made by living creatures.",
  360: "Over 17,000 islands, and Krakatoa was one of its volcanoes.",
  361: "It opened in 1914 and saves a voyage round Cape Horn.",
  362: "Two stacked pennants, bearing a sun and a moon.",
  363: "It runs roughly north-south through western Russia.",
  364: "Its outflow feeds the world's longest river.",
  365: "Rome alone would put it near the top.",
  366: "Counting every fjord and island, it beats Florida several times over.",
  367: "Not Zurich, and not Geneva.",
  368: "Sits in a bowl at around 3,600 metres; the airport is higher still.",
  369: "Its name means 'waterless place' in Mongolian.",
  370: "It rises in Colorado and empties into the Gulf of Mexico.",
  546: "It also borders Iraq, Turkey, Afghanistan and Pakistan.",
  547: "Legislative in Cape Town, judicial in Bloemfontein.",
  548: "About 8,400 metres down, north of a Caribbean island.",
  549: "Only about 800 km from the North Pole.",
  550: "Off the Queensland coast, with rainforest growing on pure sand.",
  551: "It shares the world's second-largest island with Indonesia.",
  552: "A small, very wealthy peninsula on the Persian Gulf.",
  553: "Water comes from desalination and fossil aquifers instead.",
  554: "It sits at 3,812 metres, straddling Peru and Bolivia.",
  555: "Only 82 km wide; the two countries can see each other across it.",
  556: "Bounded by the Red Sea, the Persian Gulf and the Indian Ocean.",
  557: "Both sit in the middle of the country, one just south of the other.",
  558: "More than Egypt, clustered around ancient Meroë.",

  /* ---- Food & Drink ------------------------------------------------------- */
  61:  "A pulse, blended with tahini, lemon and garlic.",
  62:  "The same spirit as a daiquiri, with mint and lime added.",
  63:  "Curdled and pressed, the way cheese is made from milk.",
  64:  "It has led the world since the 1840s, and Vietnam is second.",
  65:  "Buried in earthenware pots to ferment through the winter.",
  66:  "It takes about 150 flowers to yield a single gram.",
  67:  "The province around Guangzhou, where the tea-house tradition began.",
  68:  "The same dough is piped to make gougères and croquembouche.",
  69:  "Identified by Kikunae Ikeda in 1908; glutamate is what triggers it.",
  70:  "From the Wuyi Mountains in Fujian; it tastes of campfire.",
  279: "Trodden, pressed and left to ferment.",
  280: "A stone fruit, botanically a berry, mashed with lime and onion.",
  281: "Naples in particular claims the modern form.",
  282: "It is fermented, dried and roasted before it becomes a bar.",
  283: "They regurgitate and evaporate flower nectar to make it.",
  284: "Beaten, then set in a pan without stirring.",
  285: "Named after the American pharmacist who devised it in 1912.",
  286: "Ground with sugar into a paste; marzipan is mostly this and sugar.",
  287: "A young animal, giving pale, tender meat.",
  288: "It began as a way of preserving fish in fermented rice.",
  461: "Brewed from rice, though it is usually called a wine.",
  462: "Pounded with pine nuts, garlic, parmesan and olive oil.",
  463: "Served chilled, and the soup is famously red.",
  464: "Legend ties the shape to the 1683 siege of its capital.",
  465: "Baked, sliced, then baked again, which is the whole point.",
  466: "The same legume behind tofu, pressed and fermented for months.",
  467: "Strained through a cloth bag that stains it the colour of silk stockings.",
  468: "French for 'under vacuum'.",
  469: "Served in tulip-shaped glasses, several times a day.",
  470: "It does not melt, which is why it holds its shape in curry.",
  471: "Beef or chicken broth, rice noodles, and a fistful of herbs.",
  472: "Cooked together first, then whisked into liquid to thicken it.",
  473: "It must come from designated regions of Mexico to bear the name.",
  474: "Judged on having at least seven pleats and a translucent wrapper.",
  623: "Notoriously stringy and pungent; an acquired taste even in Japan.",
  624: "The same genus that gave the world the first antibiotic.",
  625: "The female part of the flower, hand-picked at dawn.",
  626: "Two Cantonese words; only a roaring flame and a seasoned pan produce it.",
  627: "The same acid that makes muscles ache after exercise.",
  628: "A tiny gluten-free grain, fermented into a sour flatbread.",
  629: "A fortified wine from the west of the island.",
  630: "Pressed into sheets like paper and toasted.",
  631: "Fish cured in citrus rather than cooked with heat.",
  632: "Fermented with glutinous rice; the base of bibimbap sauce.",
  633: "Dusted with icing sugar and flavoured with rosewater.",

  /* ---- History ------------------------------------------------------------ */
  21:  "Two years before the First World War began.",
  22:  "In office 1979-1990, nicknamed the Iron Lady.",
  23:  "Soviet, launched 1957; its beeping started the space race.",
  24:  "It ruled from Constantinople for six centuries.",
  25:  "The same text appeared on it in Greek, which unlocked the rest.",
  26:  "Signed in a palace hall of mirrors in 1919.",
  27:  "Britain fought to keep selling the drug there.",
  28:  "The 1340s, when perhaps a third of Europe died.",
  29:  "A formerly enslaved general who beat Napoleon's army.",
  30:  "It ended two and a half centuries of shogunate rule in 1868.",
  231: "He was followed down the ladder twenty minutes later by Buzz Aldrin.",
  232: "Two surrenders that year, in May and in August.",
  233: "He refused a third term, setting a precedent that held for 150 years.",
  234: "A centennial gift, designed by Bartholdi with a frame by Eiffel.",
  235: "The same year as Tiananmen and the Velvet Revolution.",
  236: "Shot from a book depository while riding in an open car.",
  237: "It began after an assassination in Sarajevo that June.",
  238: "It sailed from Plymouth; a compact was signed aboard.",
  239: "He was 33 at the time and later became the third president.",
  240: "An Andean empire, conquered by Pizarro a century after building it.",
  241: "A goldsmith from Mainz; his Bible was the first major book printed.",
  242: "The last active ruler of the Ptolemaic Kingdom.",
  243: "He took the name meaning 'man of steel'.",
  393: "He and his family were executed at Yekaterinburg in 1918.",
  394: "It recognised the independence of thirteen former colonies.",
  395: "He took the crown from the Pope's hands at Notre-Dame.",
  396: "The Bastille fell that July.",
  397: "It grew into the largest contiguous land empire in history.",
  398: "A tower, one of the tallest structures in the world for centuries.",
  399: "She passed her great-great-grandmother's record in 2015.",
  400: "Reactor four exploded during a safety test in April.",
  401: "It renamed itself in 1939, and the name means 'land of the free'.",
  402: "A former monk who drove the Mongols out in 1368.",
  403: "The lease on the New Territories ran out at midnight on 30 June.",
  404: "It limited the king's power and is still partly on the statute book.",
  405: "Bicycle makers from Ohio who flew at Kitty Hawk.",
  406: "It was built on an island in a lake, where Mexico City now stands.",
  407: "She won two, in different sciences, and the second was in chemistry.",
  408: "It cost about two cents an acre and was mocked as a folly.",
  573: "Brokered by the Pope, it drew a line down the Atlantic.",
  574: "He moved the capital east and gave the city his own name.",
  575: "An arrow to the eye, and an embroidered account survives.",
  576: "Two words for the same thing, one meaning 'tent government'.",
  577: "Bismarck chaired it; no African representatives attended.",
  578: "He won at Cannae but never took Rome itself.",
  579: "It reunified China and built the Grand Canal, then collapsed in decades.",
  580: "Metternich presided; it restored monarchies across the continent.",
  581: "He served from 1947 until his death in 1964.",
  582: "It ceded Hong Kong Island to Britain.",
  583: "Gagarin flew a single orbit in it in April 1961.",
  584: "A boy king whose burial goods had survived almost untouched.",
  585: "Its last sultan was deposed a year before the republic was declared.",

  /* ---- Literature --------------------------------------------------------- */
  31:  "A Belgian detective with a formidable moustache and 'little grey cells'.",
  32:  "He spent four years in a Siberian prison camp.",
  33:  "Two words; his face is on every telescreen.",
  34:  "A Colombian Nobel laureate; the town is called Macondo.",
  35:  "He took his pen name from a river in Suffolk.",
  36:  "A Beatles song title gave one of those novels its name.",
  37:  "A flat world carried on four elephants standing on a turtle.",
  38:  "One of the Four Great Classical Novels; a pilgrimage to fetch scriptures.",
  39:  "Its title comes from a Yeats poem.",
  40:  "Written in Italian in the early 1300s; Virgil guides the narrator.",
  244: "He also wrote Hamlet and Macbeth.",
  245: "She wrote the first book in Edinburgh cafés as a single mother.",
  246: "It opens with a line about a single man in possession of a good fortune.",
  247: "A Scottish doctor who tried to kill the character off at a waterfall.",
  248: "An Oxford philologist who invented the languages first.",
  249: "He also wrote Tender Is the Night; his wife was Zelda.",
  250: "She published almost nothing else for over fifty years.",
  251: "Written for a ghost-story contest at Lake Geneva when she was eighteen.",
  252: "It begins 'In the beginning'.",
  253: "A Cuban fisherman, a marlin, and eighty-four days without a catch.",
  254: "He lost the use of his left hand at the Battle of Lepanto.",
  411: "A travelling salesman wakes as a monstrous insect.",
  412: "A white whale, and a captain with one leg.",
  413: "The temperature at which paper is said to catch fire.",
  414: "His gardener companion carries him up the mountain at the end.",
  415: "He also wrote 'The Tell-Tale Heart'; the bird says 'Nevermore'.",
  416: "Set in the theocratic Republic of Gilead.",
  417: "Fourteen lines; Shakespeare wrote 154 of them.",
  418: "He also wrote a novel about a woman and Count Vronsky.",
  419: "He wrote twenty love poems and one song of despair.",
  420: "The pigs stand for something other than pigs.",
  421: "A pilot crashes in the Sahara and meets a boy from an asteroid.",
  422: "Named after an extinct Native American people of Massachusetts.",
  423: "Seventeen syllables, usually with a seasonal reference.",
  424: "A Nobel laureate; the novel is haunted by a dead child.",
  586: "A lady-in-waiting at the Heian court around the year 1000.",
  587: "It follows one Dublin day, 16 June 1904.",
  588: "Gray wrote a famous one in a country churchyard.",
  589: "An axe, a pawnbroker, and a theory about extraordinary men.",
  590: "Pilgrims riding to Becket's shrine, each telling a story.",
  591: "He won in 1986; his plays include Death and the King's Horseman.",
  592: "The neighbour who rents the small house next door.",
  593: "He is arrested one morning and never learns the charge.",
  594: "Its narrator lives in a basement lit by 1,369 bulbs.",
  595: "Three-line stanzas with an interlocking aba, bcb rhyme.",
  596: "It opens with a line about happy families all being alike.",
  597: "Narrated by Chief Bromden in an Oregon psychiatric ward.",

  /* ---- Film & TV ---------------------------------------------------------- */
  41:  "It won the Best Animated Feature Oscar in 2003.",
  42:  "The other choice would have sent him back to sleep.",
  43:  "Hidden behind a holographic shield, rich in vibranium.",
  44:  "The 1980s, a girl with a shaved head, and a monster world called the Upside Down.",
  45:  "Taken from the physicist of the uncertainty principle.",
  46:  "Known for smeared step-printed slow motion and Christopher Doyle's camera.",
  47:  "Its computer sings 'Daisy Bell' as it is shut down.",
  48:  "He also made Memories of Murder and Snowpiercer.",
  49:  "He died in 1973, weeks before Enter the Dragon opened.",
  50:  "A silent film about First World War fighter pilots.",
  255: "He finally won an Oscar for The Revenant, decades later.",
  256: "George Lucas created it; the first film came out in 1977.",
  257: "A snowy owl, delivered as a birthday present from Hagrid.",
  258: "Its plot borrows heavily from Hamlet.",
  259: "An orange sofa, and Gunther behind the counter.",
  260: "Steve Jobs bought it from Lucasfilm before it made the film.",
  261: "He was largely uninsurable before the role turned his career around.",
  262: "The mechanical shark broke down so often it barely appears.",
  263: "It tells its story out of chronological order, in chapters.",
  264: "It swept all five major Oscars in 1992.",
  265: "It has aired since 1989 and is set in Springfield.",
  266: "The highest-grossing film of all time, twice over.",
  267: "Follow the yellow brick road, and it is the colour of the gem.",
  425: "Room 237, a hedge maze, and 'all work and no play'.",
  426: "The tagline promised that in space no one can hear you scream.",
  427: "He also made Apocalypse Now.",
  428: "A small terrier who pulls back the curtain.",
  429: "Stainless steel, gull-wing doors, and a famously bad sales record.",
  430: "Two sisters, a rural house, and a large forest spirit.",
  431: "He also played Forrest Gump and Captain Miller.",
  432: "A mockumentary with a paper company and a camera crew nobody explains.",
  433: "Spanish for 'cloud island', off the coast of Costa Rica.",
  434: "He took over from Connery and made the role lighter.",
  435: "A tiny principality that turns out to belong to Julie Andrews.",
  436: "He also made The Birds and Rear Window.",
  437: "Its name may derive from an old English village of fools.",
  438: "Elderly, hunched, and fond of steepling his fingers.",
  439: "The first rule is that you do not talk about it.",
  440: "Three letters, and she carries a plant in her chest cavity.",
  441: "Three films, the last set in Paris.",
  442: "A domed set town, and a sun that is a stage light.",
  443: "A pineapple under the sea.",
  444: "Canned pineapple with an expiry date, and California Dreamin' on repeat.",
  598: "Directed by Frank Capra; a runaway heiress and a reporter.",
  599: "Remade in Hollywood as a Western with gunfighters.",
  600: "The camera arcs around a frozen moment as the hero dodges.",
  601: "Modelled on Hearst's papers; the sled is called Rosebud.",
  602: "She never once attended the ceremony to collect them.",
  603: "Two moles, one in the police and one in the triad.",
  604: "Narrated by a boy with a camera called Rocket.",
  605: "Beethoven's Ninth, milk bars, and a bowler hat.",
  606: "Three letters, one shifted from IBM, and it will not open the pod bay doors.",
  607: "Season two moves to the docks, season four to the schools.",
  608: "He also directed Blue Velvet and Mulholland Drive.",
  609: "Fritz Lang directed it; a city divided between workers and thinkers.",
  610: "Doves, slow motion, and two guns at once.",

  /* ---- Science & Nature --------------------------------------------------- */
  11:  "Inert enough that we breathe it in and out unchanged.",
  12:  "Two letters, from the Latin 'aurum'.",
  13:  "Two on top that receive, two below that pump.",
  14:  "It orbits the nucleus and carries the current in a wire.",
  15:  "Named after a German physicist; its symbol is the last Greek letter.",
  16:  "The biggest planet also spins the fastest — under ten hours.",
  17:  "About 8% of the crust, and we wrap food in it.",
  18:  "From the Greek 'mykes'; it covers mushrooms and moulds.",
  19:  "His letter from Indonesia forced Darwin to publish.",
  20:  "Two words; cross it and even light cannot come back.",
  216: "Two hydrogen atoms bonded to one oxygen.",
  217: "A baby has far more; many fuse as we grow.",
  218: "Its Great Red Spot is a storm larger than Earth.",
  219: "Iron oxide dust gives it the colour.",
  220: "Around two square metres of it, and it weighs several kilos.",
  221: "One fewer since 2006.",
  222: "The top of the Celsius scale as originally defined.",
  223: "It scores 10 on the Mohs scale.",
  224: "About eight light-minutes away.",
  225: "It has its own DNA and was probably once a separate organism.",
  226: "He published it in 1915, a decade after the special theory.",
  227: "Two letters, from the Latin 'argentum'.",
  228: "It lacks both A and B antigens and the Rh factor.",
  229: "Three words; the middle one is the sugar in its backbone.",
  230: "Fast enough to circle the Earth seven times in a second.",
  371: "It runs from hip to knee and is about a quarter of your height.",
  372: "About 3 mm long, and named after a piece of riding tack.",
  373: "It sits behind the stomach and also makes digestive enzymes.",
  374: "The same number as the human heart has chambers.",
  375: "It can regrow to full size from a fraction of itself.",
  376: "More than a human has hearts, fewer than an octopus has arms plus one.",
  377: "Visible to the naked eye, just about, at 0.1 mm.",
  378: "Around 8 kg of it, in a deep-diving marine mammal.",
  379: "Over 300 km/h in a stoop, faster than any cheetah.",
  380: "About 5 cm long and found only in Cuba.",
  381: "About three quarters of all ordinary matter.",
  382: "One letter, from the Latin 'kalium'.",
  383: "Discovered in 1789, eight years after the planet itself.",
  384: "The same gas we breathe out.",
  385: "Exactly halfway between battery acid and drain cleaner.",
  386: "It overtook Jupiter in 2023 with a haul of new discoveries.",
  387: "Deer and rabbits do it; neither nocturnal nor diurnal.",
  388: "A filter feeder, up to 18 metres, and harmless to people.",
  389: "The one in citrus fruit; sailors lacked it at sea.",
  390: "Forty-six chromosomes in total.",
  391: "Dry ice does it; so does frost disappearing on a cold morning.",
  392: "One of the three rock types, alongside sedimentary and metamorphic.",
  559: "Not what a disease does, but why it started.",
  560: "Massless, and it is also the particle of light.",
  561: "It makes up about a quarter of the crust and most of the sand.",
  562: "Named after the Frenchman who discovered radioactivity.",
  563: "Its opposite is aphelion.",
  564: "The 'little brain' tucked under the back of the skull.",
  565: "Squeeze a gas into half the space and the pressure doubles.",
  566: "The only moon with a thick atmosphere; Huygens landed on it.",
  567: "Helium nuclei, stopped by skin — but dangerous if inhaled.",
  568: "Named after a French mathematician; one newton per square metre.",
  569: "Greek for 'cell eating'; white blood cells do it to bacteria.",
  570: "It is also the answer to what the hardest natural substance is.",
  571: "Mammals and birds are these; reptiles are not.",
  572: "It leaves the left ventricle and arches over the heart.",

  /* ---- Odds & Ends -------------------------------------------------------- */
  111: "Named after the swift messenger of the Roman gods.",
  112: "The Babylonians chose it because it divides so many ways.",
  113: "The only zodiac sign represented by an object, not a living thing.",
  114: "Not the euro — the country stayed out.",
  115: "A nod to their reputation for wisdom.",
  116: "One systemic, and one for each set of gills.",
  117: "The same metal as the second-place medal.",
  118: "Sixty times twenty-four times seven.",
  119: "Named after an American aviator who crash-landed on top of it.",
  120: "It sounds like the word for wealth, which is why buildings skip other floors.",
  321: "One more than usual, because February gains a day.",
  322: "Also the word for a feeling of self-respect.",
  323: "Bees build their combs from them.",
  324: "Its heart alone weighs about 180 kg.",
  325: "The same number as the days of the week.",
  326: "It can hit 100 km/h but only for about twenty seconds.",
  327: "The same number as the colours traditionally counted in a rainbow.",
  328: "Its neck contains the same number of vertebrae as yours.",
  329: "Thirteen ranks in each of four suits.",
  330: "An octagon, chosen so it is recognisable from behind.",
  331: "Domesticated from wolves at least 15,000 years ago.",
  332: "Eight rows of eight.",
  333: "Sixty times twenty-four.",
  334: "Sixty times sixty.",
  335: "The clue is in the prefix.",
  336: "The most common type, paired with the most common Rh factor.",
  337: "One has a duck's bill; the other is covered in spines.",
  338: "It is also what a jury might convict you of.",
  339: "Also the word for where children learn.",
  340: "Including four wisdom teeth, if they came through.",
  341: "It has research stations, but nobody stays for life.",
  342: "One for each hour, in theory — the real map is messier.",
  343: "Not the study of meteors, despite the name.",
  344: "Eight pawns and eight pieces per side.",
  345: "It cannot fly, and it lays the largest egg.",
  346: "The hardest substance, for the longest marriage.",
  347: "It beats its wings in a figure of eight.",
  348: "A grimmer collective noun than the one for crows, if anything.",
  349: "Many later fuse, leaving 206 in an adult.",
  350: "It would need a state name with a 'qu' in it.",
  519: "The same word as a disorderly crowd.",
  520: "A different word applies when they are on the ground.",
  521: "From the Latin 'claustrum', a bolt or enclosed place.",
  522: "From the Greek for spider, which is also the name of the class.",
  523: "Greek for 'love charm'; nobody agrees what it is for.",
  524: "One and six, two and five, three and four.",
  525: "The metal of the first-place medal.",
  526: "A thousand million, not the older British million million.",
  527: "Kona is the region; it is also the only US state that grows vanilla.",
  528: "The prefix is the same as in 'decade'.",
  529: "Bears and humans both qualify.",
  530: "180 degrees above freezing on that scale.",
  531: "Named after the noise they are famous for making.",
  532: "Superior, Michigan, Huron, Erie and one more.",
  533: "Its output is a seismogram, measured on a moment magnitude scale.",
  534: "From the Greek for cave.",
  535: "Hospitals in the region often skip that floor number.",
  536: "'Listen' and 'silent' are one of these.",
  537: "It drove the spice trade long before chilli reached Europe.",
  538: "The word describes what touching one feels like.",
  539: "Its Greek equivalent is Poseidon.",
  540: "It comes round every four years, with exceptions at some centuries.",
  541: "Not red — the other two of the three primaries.",
  542: "From the Greek for 'bounding circle'.",
  543: "Two fewer than a guitar.",
  544: "Around 21 December in the northern hemisphere.",
  545: "It is also the name of the closest planet to the Sun.",
  677: "Fittingly violent, for an animal that charges.",
  678: "It contains the Greek for thirteen, and there is a word for it.",
  679: "Eight in the wrist alone, and five in the palm.",
  680: "Each face is a pentagon.",
  681: "It used to span one more before a 2010 reform.",
  682: "The word also describes something that floats.",
  683: "Employers once used it for hiring; it has no scientific basis.",
  684: "Over 96% of it, which is why the surface is 460°C.",
  685: "Literally fear of the marketplace.",
  686: "Each face is a triangle, and it is the shape of a d20.",
  687: "An oddly corporate word for a group of small mustelids.",
  688: "Roughly the light of one ordinary wax candle.",
  689: "Building the family tree, not reading the DNA.",
  690: "Latin, used when there are too many authors to list.",
  691: "A haiku plus two more lines of seven syllables.",
  692: "Perhaps the most charming collective noun in English.",
  693: "From the Greek 'nomisma', meaning coin.",
  694: "'SWIMS' upside down still reads the same.",
  695: "From the Latin for one hundred.",

  409: "A grand codename for the whole operation; the landings themselves were Neptune.",
  410: "The same dynasty that built the Forbidden City.",

  /* ---- Art & Architecture -------------------------------------------------- */
  71:  "Painted from an asylum window at Saint-Rémy in 1889.",
  72:  "Melting clocks, lobster telephones, and a waxed moustache.",
  73:  "Quarried at Carrara, from a block other sculptors had abandoned.",
  74:  "Still unfinished after more than 140 years.",
  75:  "From the series Thirty-six Views of Mount Fuji.",
  76:  "The pigment binds as the plaster dries, so you cannot correct it.",
  77:  "A Japanese artist who has lived voluntarily in a psychiatric institution since 1977.",
  78:  "It succeeded Romanesque and gave us Notre-Dame and Chartres.",
  79:  "Also home to the Mona Lisa and a glass pyramid.",
  80:  "Two Cantonese words for the narrow pre-war blocks with balconies over the pavement.",
  289: "It hangs behind bulletproof glass and is smaller than most expect.",
  290: "He considered himself a sculptor and resented the commission.",
  291: "Mix any two and you get orange, green or purple.",
  292: "He also silkscreened Marilyn and predicted fifteen minutes of fame.",
  293: "Originally conceived as Dante, sitting above the Gates of Hell.",
  294: "A monochrome protest at the bombing of a Basque town in 1937.",
  295: "Ants, a barren landscape, and time going soft.",
  475: "A critic coined the name as an insult in 1874.",
  476: "The Byzantines covered whole church interiors in it.",
  477: "He also engineered the internal frame of the Statue of Liberty.",
  478: "Seurat's method; the eye does the mixing, not the palette.",
  479: "Sometimes called the Mona Lisa of the North.",
  480: "The repair is highlighted rather than hidden, as part of the object's history.",
  481: "A Bauhaus director who later built the Seagram Building.",
  482: "Home of the Medici, Brunelleschi's dome and the Uffizi.",
  483: "Built for Vishnu in the 12th century; it appears on a national flag.",
  484: "A British-Indian sculptor; the surface has no visible seams.",
  485: "The Chrysler Building's spire is its purest expression.",
  486: "Two Chinese characters; the raised platform the performers occupy.",
  634: "A Netherlandish triptych of paradise, indulgence and hell.",
  635: "Three panels; the word shares a root with 'tripod'.",
  636: "He pushed abstraction to a single shape on a white ground.",
  637: "Italian for 'smoky'; it is why the Mona Lisa has no hard outlines.",
  638: "Its shells took sixteen years and bankrupted the budget.",
  639: "His father and grandfather were sculptors; his hang from the ceiling.",
  640: "Reading the symbols rather than judging the brushwork.",
  641: "Married to Frida Kahlo; the mural was destroyed for including Lenin.",
  642: "An American architect whose Fallingwater sits over a waterfall.",
  643: "Brunelleschi demonstrated it; parallel lines converge on the horizon.",
  644: "Two words in Chinese; tone and gradation matter more than hue.",
  758: "Vienna, 1908, and the two figures are wrapped in gold leaf.",
  759: "It began as part of the same commission as his seated thinker.",
  760: "He painted his own pond at Giverny again and again.",
  761: "In Normandy, where he built the Japanese bridge.",
  762: "In Normandy, and he rented a room opposite to paint the façade.",
  763: "Stacks of harvested cereal, painted across the seasons.",
  764: "A goddess arriving on a shell, painted in Florence around 1485.",
  765: "A militia company portrait, and the darkness turned out to be varnish.",
  766: "The models were his sister and his dentist.",
  767: "A corner diner at night, seen through a curved window.",
  768: "A Belgian who also painted a pipe that was not a pipe.",
  769: "Its title is about representation itself, not about smoking.",
  770: "He painted himself into the canvas, at his easel.",
  771: "A man in a white shirt with his arms flung up before a firing squad.",
  772: "Painted directly onto the walls of his own house.",
  773: "An American in London who insisted the picture was about arrangement, not sentiment.",
  774: "The woman had polio; the house is in Maine.",
  775: "A cart in a shallow river in Suffolk.",
  776: "A ghostly white sailing ship under tow by a steam tug.",
  777: "A figure seen from behind, standing on a rocky outcrop.",
  778: "Survivors of a French naval wreck, abandoned on a makeshift float.",
  779: "The horse rears; the reality was a mule.",
  780: "Dappled sunlight through the trees in Montmartre.",
  781: "Provençal peasants at a table, painted five times.",
  782: "A limestone ridge near Aix-en-Provence.",
  783: "Parisians on an island in the Seine, built from optical dots.",
  784: "He left a stockbroking career and died in French Polynesia.",
  785: "Painted in Arles to decorate a room for a visiting friend.",
  786: "Painted in Arles; the terrace is still there today.",
  787: "The Nazis seized it; a long restitution case followed.",
  788: "Warmer tones, harlequins and circus performers.",
  789: "Five figures from a Barcelona brothel street, faces borrowed from African masks.",
  790: "Motion broken into overlapping planes; a critic called it an explosion in a shingle factory.",
  791: "De Stijl, and the compositions are named after boogie-woogie.",
  792: "He worked from all four sides, calling it action painting.",
  793: "Their arrangement is meant to be viewed from very close up.",
  794: "Based on a drawing by a 16th-century Spanish friar.",
  795: "One in European dress, one in Tehuana, connected by an artery.",
  796: "Carved when he was 24; the only work he ever signed.",
  797: "The bronze original is lost; only Roman marble copies survive.",
  798: "The god leaps from his chariot; the sky is lapis blue.",
  799: "A merchant, his wife, and a signature saying the painter was here.",
  800: "A Flemish painter who set the biblical tower in a Antwerp-like port.",
  801: "Two envoys, a table of instruments, and anamorphosis.",
  802: "Stainless steel made to look like a party balloon.",
  803: "A stencil that shredded itself at auction in 2018.",
  804: "The model posed in a bath and caught a chill.",
  805: "Post stations along the road between Edo and Kyoto.",
  806: "So abstract that US customs taxed it as a metal object, not art.",
  807: "A married pair who also wrapped the Reichstag.",
  808: "A barmaid, a marble counter, and a reflection that does not add up.",
  809: "A bishop pushes the swing; a young man watches from below.",
  810: "It followed the Baroque and preceded Neoclassicism.",
  811: "The first freestanding nude bronze cast since antiquity.",
  812: "Ten gilded bronze panels, and he spent 27 years on them.",
  813: "The national museum on Museumplein, reopened in 2013 after a decade.",
  814: "Its name means 'offices'; it was built for Medici administration.",
  815: "It returned from New York in 1981, after Franco's death.",

  /* ---- Music --------------------------------------------------------------- */
  51:  "Fifty-two white and thirty-six black.",
  52:  "Tuned in fifths: G, D, A and E.",
  53:  "Named after the London street where the studio stands.",
  54:  "A prism splitting white light on the sleeve.",
  55:  "Its opposite marking is 'piano'.",
  56:  "The number of keys, white and black, from one C to the next.",
  57:  "Two words; the bow is threaded between the strings.",
  58:  "A rival was rumoured, wrongly, to have poisoned him.",
  59:  "Two words; moveable bridges sit under each string.",
  60:  "Italian, and it means 'in the manner of the chapel'.",
  268: "He recorded at Sun Studio in Memphis and lived at Graceland.",
  269: "John, Paul, George and Ringo.",
  270: "The best-selling album of all time, released in 1982.",
  271: "The name is an acronym of the four members' first names.",
  272: "Two more than a violin has.",
  273: "He conducted the premiere of his Ninth and could not hear the applause.",
  274: "A red-haired priest who taught at a Venetian orphanage.",
  275: "Nicknamed Satchmo; he also sang 'What a Wonderful World'.",
  276: "He won the Nobel Prize in Literature in 2016.",
  277: "The lyrics come from a poem written during the War of 1812.",
  278: "Six minutes long, with an operatic section and no chorus.",
  445: "She sang 'Respect' and 'Natural Woman'.",
  446: "Meat dress, 2010 VMAs.",
  447: "Its metal cousin is the glockenspiel.",
  448: "Vienna's unofficial anthem, played every New Year.",
  449: "From Detroit; one of his albums is named after his real name.",
  450: "Fast, slow, a dance, then a fast finale.",
  451: "Born of blues, ragtime and brass bands in Storyville.",
  452: "Three words describing how fast a track is.",
  453: "Monks played it as meditation rather than performance.",
  454: "The largest instrument in the string section, played standing.",
  455: "One melody, one crescendo, seventeen minutes, no development.",
  456: "Born in Minneapolis; he once changed his name to an unpronounceable symbol.",
  457: "Its opposite is diminuendo.",
  458: "Struck with a padded stick to keep time during sutra chanting.",
  459: "The one you get playing only the white keys from its root.",
  460: "Three days of mud, and Hendrix closed it on the Monday morning.",
  611: "Italian, and it sits above allegro on the tempo ladder.",
  612: "The choreography was Nijinsky's; the audience came to blows.",
  613: "Seven semitones, and the most consonant interval after the octave.",
  614: "Four movements: Acknowledgement, Resolution, Pursuance, Psalm.",
  615: "Written with a small numeral 3 above the beam.",
  616: "It has sympathetic strings that resonate untouched.",
  617: "Below mezzo-soprano, and rarer than either voice above it.",
  618: "He died three months after its poorly received premiere.",
  619: "He also conducted the New York Philharmonic for over a decade.",
  620: "Bach's fugues are the textbook case.",
  621: "The drum is a barrel-shaped buk, and one singer plays every role.",
  622: "Two fewer than a major scale, and it is what the black keys give you.",
  696: "He left Poland at twenty and never returned.",
  697: "It actually takes closer to two minutes to play properly.",
  698: "Composed at a monastery on Mallorca during a wet winter.",
  699: "News reached him in Stuttgart, and he wrote it in fury.",
  700: "Smuggled there in a jar of cognac by his sister.",
  701: "One is a triple-time village dance, the other a stately processional.",
  702: "He taught, performed in salons and died there in 1849.",
  703: "Originally dedicated to Napoleon, until he crowned himself.",
  704: "The rhythm was later used as the Morse code V for victory.",
  705: "The nickname came from a critic comparing it to a lake in Lucerne.",
  706: "A short, light piece; the title means 'trifle'.",
  707: "A wife disguises herself as a prison guard to rescue her husband.",
  708: "It has five movements and a thunderstorm.",
  709: "A German poet and playwright who also wrote a William Tell drama.",
  710: "It is a serenade in G major, and the title is German.",
  711: "The king of the Roman gods.",
  712: "The statue is of a man the protagonist killed in the first scene.",
  713: "His birthplace is now a museum on Getreidegasse.",
  714: "Two books, 48 pairs, and it proved equal temperament worked.",
  715: "Written, the story goes, to help a count get to sleep.",
  716: "Its authorship is disputed, but it is a staple of horror films.",
  717: "Each of the four concertos comes with an accompanying sonnet.",
  718: "It opens Act III of Die Walkure.",
  719: "Four operas, about fifteen hours, one cursed piece of gold.",
  720: "Written in 24 days; audiences traditionally stand for it.",
  721: "Performed on barges on the Thames in 1717.",
  722: "He wrote it while directing a conservatory in New York.",
  723: "Written as veiled protest against Russian censorship.",
  724: "He also wrote the Piano Concerto in A minor.",
  725: "It commemorates the repulse of Napoleon's invasion of Russia.",
  726: "One about a swan, one about a sleeper, one about Christmas.",
  727: "Not related to the waltz-writing family of the same surname.",
  728: "Named after Bergamo; the third movement is the famous one.",
  729: "He suppressed it in his lifetime, fearing it damaged his reputation.",
  730: "The bird is a flute, the duck an oboe, the wolf three horns.",
  731: "Seven movements, one per planet known at the time, minus Earth.",
  732: "An American folk opera set in Catfish Row, Charleston.",
  733: "Written in memory of a friend's exhibition; Ravel orchestrated it.",
  734: "Set to medieval Latin and Middle High German poems.",
  735: "Fourteen portraits of his friends, with a hidden theme he never revealed.",
  736: "Adapted from the slow movement of his own string quartet.",
  737: "Baroque, German, and the piece was obscure until the 1970s.",
  738: "Commissioned for Cairo, around the time the Suez Canal opened.",
  739: "A US naval officer, a fifteen-year-old bride, and a betrayal.",
  740: "Set in Peking; the prince must solve three riddles.",
  741: "A Swiss folk hero and an apple on a boy's head.",
  742: "A prequel, in story terms, to Mozart's Marriage of Figaro.",
  743: "He invented the solo piano recital and was mobbed like a pop star.",
  744: "It has only two completed movements, and nobody knows why.",
  745: "The nickname counts the performers at its vast 1910 premiere.",
  746: "He wrote it while the city was encircled; the score left on microfilm.",
  747: "Dedicated to the hypnotherapist who treated his writer's block.",
  748: "He was so agile that rumours spread he had sold his soul.",
  749: "Set in the Appalachians; Martha Graham choreographed it.",
  750: "Six symphonic poems about Bohemian landscape and legend.",
  751: "He founded a one-member church and left 84 identical handkerchiefs.",
  752: "The year its greatest composer died, which is how the boundary was drawn.",
  753: "It brought bigger orchestras, programme music and national schools.",
  754: "One of them puts a single player in dialogue with the whole ensemble.",
  755: "It plays before the curtain rises.",
  756: "Italian for 'little book'.",
  757: "A chemist by profession, and one of the Mighty Handful.",
};

/* ---- Validation ---------------------------------------------------------- */

const norm = (s) =>
  String(s ?? "")
    .toLowerCase()
    .normalize("NFD")
    .replace(/[\u0300-\u036f]/g, "")
    .replace(/[^a-z0-9\s]/g, " ")
    .replace(/\s+/g, " ")
    .trim();

/** Whole-word containment, so "C" does not match every word with a c in it. */
function containsPhrase(haystack, needle) {
  const h = norm(haystack);
  const n = norm(needle);
  if (!n) return false;
  /* One- and two-character answers ("K", "C", "e") cannot be avoided in prose;
     for those only an exact match counts as a leak. */
  if (n.length <= 2) return h === n;
  return new RegExp(`(^|\\s)${n.replace(/[.*+?^${}()|[\]\\]/g, "\\$&")}(\\s|$)`).test(h);
}

const byId = new Map(bank.questions.map((q) => [q.id, q]));
const problems = [];
let applied = 0;

for (const [rawId, hint] of Object.entries(HINTS)) {
  const id = Number(rawId);
  const q = byId.get(id);
  if (!q) { problems.push(`#${id} not in bank`); continue; }

  if (!hint || hint.trim().length < 12) {
    problems.push(`#${id} hint too short to be useful: "${hint}"`);
    continue;
  }
  if (containsPhrase(hint, q.answer)) {
    problems.push(`#${id} hint contains the answer "${q.answer}": "${hint}"`);
    continue;
  }
  for (const alias of q.accept || []) {
    if (containsPhrase(hint, alias)) {
      problems.push(`#${id} hint contains accepted alias "${alias}": "${hint}"`);
      break;
    }
  }

  q.hint = hint.trim();
  applied++;
}

if (problems.length) {
  console.error(`FAILED — ${problems.length} problem(s), nothing written:`);
  for (const p of problems) console.error("  -", p);
  process.exit(1);
}

if (!dry) writeFileSync(bankPath, JSON.stringify(bank, null, 2) + "\n");

const withHint = bank.questions.filter((q) => q.hint).length;
console.log(`${dry ? "would apply" : "applied"} ${applied} hints`);
console.log(`coverage: ${withHint}/${bank.questions.length} (${((withHint / bank.questions.length) * 100).toFixed(1)}%)`);

if (report) {
  const missing = {};
  for (const q of bank.questions) {
    if (!q.hint) (missing[q.category] ??= []).push(q.id);
  }
  console.log("\nstill missing, by category:");
  for (const [cat, ids] of Object.entries(missing).sort((a, b) => b[1].length - a[1].length)) {
    console.log(`  ${String(ids.length).padStart(4)}  ${cat}`);
  }
}
